# ======================================================================
# BUILD AND DEPLOY PIPELINE
# ======================================================================
# Runs when a release has been tagged with a v1.0.0 like tag
# ======================================================================
name: 'Build/Deploy Nugets'

on:
  push:
    tags:
    - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      packages: write
    
    steps:    
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v3
      with:
        # Semantic version range syntax or exact version of a dotnet version
        dotnet-version: '8.0.x'
    
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
        
    - name: Restore
      run: dotnet restore ./ThingsLibrary.Schema.sln
      
    - name: Build
      run: dotnet build ./ThingsLibrary.Schema.sln --configuration Release /p:Version=${VERSION} --no-restore
      
    - name: Test
      run: dotnet test ./ThingsLibrary.Schema.sln --configuration Release /p:Version=${VERSION} --no-build
    
    - name: Pack
      run: dotnet pack ./ThingsLibrary.Schema.sln -v normal -c Release /p:Version=${VERSION} --no-restore --no-build
      if: success()
      
    - name: Push
      run: dotnet nuget push **/*.nupkg --api-key ${GITHUB_TOKEN} --source "https://nuget.pkg.github.com/things-library/index.json" --skip-duplicate
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
