# ======================================================================
# PULL Request: Build / Test
# ======================================================================
name: 'Pull Request Builder'

on:
  push:
    branches:
      - main
    paths:
      - src/**
      - tests/**
  pull_request:
    branches:
      - main
    paths:
      - src/**
      - tests/**

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    env:
      # We are going to build just the deploy projects and push those nuget packages
      SOLUTION_PATH: './ThingsLibrary.Schema.sln'

    steps:    
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET 8.0.x
      uses: actions/setup-dotnet@v3
      with:        
        dotnet-version: '8.0.x'

    - name: Setup .NET 9.0.x
      uses: actions/setup-dotnet@v3
      with:        
        dotnet-version: '9.0.x'

    - name: Display dotnet version
      run: dotnet --version

    - name: List NuGet Package Sources
      run: dotnet nuget list source
    
    - name: Restore
      run: dotnet restore ${{env.SOLUTION_PATH}}
      
    - name: Build
      run: dotnet build ${{env.SOLUTION_PATH}} --configuration Release --no-restore
      
    - name: Test
      run: dotnet test ${{env.SOLUTION_PATH}} -c Release --nologo --no-build --results-directory "./Artifacts/Test/0.0.0" /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

    - name: File Tree
      run: tree -a ./Artifacts
